# Form implementation generated from reading ui file 'WindowLimitSwitch.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LimitSwitch(object):
    def setupUi(self, LimitSwitch):
        LimitSwitch.setObjectName("LimitSwitch")
        LimitSwitch.resize(460, 380)
        LimitSwitch.setStyleSheet("QWidget {    \n"
                                  "    color: white;\n"
                                  "    background-color: #121212;\n"
                                  "    font-size: 14pt;\n"
                                  "    font-weight: 600;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton {    \n"
                                  "    border-style: solid;\n"
                                  "    border-width: 3px;\n"
                                  "    border-radius: 10px;\n"
                                  "    border-color: #38BD80;\n"
                                  "    font: bold 16px;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:hover {    \n"
                                  "    background-color: #292927;\n"
                                  "}")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(LimitSwitch)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_limit_switch_1 = QtWidgets.QLabel(LimitSwitch)
        self.label_limit_switch_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_limit_switch_1.setObjectName("label_limit_switch_1")
        self.verticalLayout.addWidget(self.label_limit_switch_1)
        self.label_limit_switch_2 = QtWidgets.QLabel(LimitSwitch)
        self.label_limit_switch_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_limit_switch_2.setObjectName("label_limit_switch_2")
        self.verticalLayout.addWidget(self.label_limit_switch_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_li_sw_save = QtWidgets.QPushButton(LimitSwitch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_li_sw_save.sizePolicy().hasHeightForWidth())
        self.pushButton_li_sw_save.setSizePolicy(sizePolicy)
        self.pushButton_li_sw_save.setMinimumSize(QtCore.QSize(215, 50))
        self.pushButton_li_sw_save.setObjectName("pushButton_li_sw_save")
        self.horizontalLayout.addWidget(self.pushButton_li_sw_save)
        self.pushButton_li_sw_cancel = QtWidgets.QPushButton(LimitSwitch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_li_sw_cancel.sizePolicy().hasHeightForWidth())
        self.pushButton_li_sw_cancel.setSizePolicy(sizePolicy)
        self.pushButton_li_sw_cancel.setMinimumSize(QtCore.QSize(215, 50))
        self.pushButton_li_sw_cancel.setObjectName("pushButton_li_sw_cancel")
        self.horizontalLayout.addWidget(self.pushButton_li_sw_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(LimitSwitch)
        QtCore.QMetaObject.connectSlotsByName(LimitSwitch)

    def retranslateUi(self, LimitSwitch):
        _translate = QtCore.QCoreApplication.translate
        LimitSwitch.setWindowTitle(_translate("LimitSwitch", "Настройка датчика высоты для TEVO Black Widow"))
        self.label_limit_switch_1.setText(_translate("LimitSwitch", "Настройки для датчика концевика"))
        self.label_limit_switch_2.setText(_translate("LimitSwitch", "применятся автоматически"))
        self.pushButton_li_sw_save.setText(_translate("LimitSwitch", "Сохранить"))
        self.pushButton_li_sw_cancel.setText(_translate("LimitSwitch", "Отмена"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    LimitSwitch = QtWidgets.QWidget()
    ui = Ui_LimitSwitch()
    ui.setupUi(LimitSwitch)
    LimitSwitch.show()
    sys.exit(app.exec())
