# Form implementation generated from reading ui file 'WindowMAIN.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(460, 380)
        Main.setStyleSheet("QWidget {    \n"
                           "    color: white;\n"
                           "    background-color: #121212;\n"
                           "    font-weight: 600;\n"
                           "}\n"
                           "\n"
                           "QPushButton {    \n"
                           "    border-style: solid;\n"
                           "    border-width: 3px;\n"
                           "    border-radius: 10px;\n"
                           "    border-color: #FE5656;\n"
                           "    font: bold 16px;\n"
                           "}\n"
                           "\n"
                           "QPushButton#pushButton_to_firmware {    \n"
                           "    border-color: #38BD80\n"
                           "}\n"
                           "\n"
                           "QPushButton:hover {    \n"
                           "    background-color: #292927;\n"
                           "}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Main)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_to_firmware = QtWidgets.QPushButton(Main)
        self.pushButton_to_firmware.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_to_firmware.sizePolicy().hasHeightForWidth())
        self.pushButton_to_firmware.setSizePolicy(sizePolicy)
        self.pushButton_to_firmware.setMinimumSize(QtCore.QSize(340, 70))
        self.pushButton_to_firmware.setStyleSheet("")
        self.pushButton_to_firmware.setObjectName("pushButton_to_firmware")
        self.verticalLayout.addWidget(self.pushButton_to_firmware)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_to_blt = QtWidgets.QPushButton(Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_to_blt.sizePolicy().hasHeightForWidth())
        self.pushButton_to_blt.setSizePolicy(sizePolicy)
        self.pushButton_to_blt.setMinimumSize(QtCore.QSize(215, 50))
        self.pushButton_to_blt.setObjectName("pushButton_to_blt")
        self.horizontalLayout.addWidget(self.pushButton_to_blt)
        self.pushButton_to_li_sw = QtWidgets.QPushButton(Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_to_li_sw.sizePolicy().hasHeightForWidth())
        self.pushButton_to_li_sw.setSizePolicy(sizePolicy)
        self.pushButton_to_li_sw.setMinimumSize(QtCore.QSize(215, 50))
        self.pushButton_to_li_sw.setStyleSheet("")
        self.pushButton_to_li_sw.setObjectName("pushButton_to_li_sw")
        self.horizontalLayout.addWidget(self.pushButton_to_li_sw)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Настройка датчика высоты для TEVO Black Widow"))
        self.pushButton_to_firmware.setText(_translate("Main", "Выберите папку с прошивкой"))
        self.pushButton_to_blt.setText(_translate("Main", "Для BLTouch"))
        self.pushButton_to_li_sw.setText(_translate("Main", "Для концевика"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QWidget()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec())
